---
title: "Seriation"
---

```{r load}
library(dplyr)
library(ca)
library(plotrix)
library(kableExtra)

# read data
data <- read.csv("seriate.allen.phase.csv")

# Row sums
(RS <- rowSums(data[, -(1)]))

# Column sums
CS <- colSums(data[, -(1)])
as.matrix(CS)
burial_ct <- data[, -(1)]
labels <- paste0(data$Burial)
rownames(burial_ct) <- labels
burial_pct <- burial_ct / RS  * 100
```

```{r ca, out.width = "100%", dpi = 300, echo=TRUE, warning=FALSE}
burial_ca <- ca(burial_ct)
plot.ca(burial_ca, labels=c(0, 2), cex = .75)

# Correspondence Analysis Ordering on Dimension 1
(ca_ord <- order(burial_ca$rowcoord[, 1]))
```

```{r decorana, out.width = "100%", dpi = 300, echo=TRUE, warning=FALSE}
library(vegan)
burial_dec <- decorana(burial_ct)
# Decorana Ordering on Projection 1
(dec_ord <- order(burial_dec$rproj[, 1]))
(cor.test(ca_ord, dec_ord, method = "kendall"))
detach("package:vegan")
detach("package:permute")
```

```{r seriation, out.width = "100%", dpi = 300, echo=TRUE, warning=FALSE}
library(seriation)
burial_dist <- dist(burial_pct, method="manhattan")
# Distance matrix:
round(burial_dist, 1)
set.seed(42)
burial_ser1 <- seriate(burial_dist, method="ARSA")
burial_ser2 <- seriate(burial_dist, method="BBURCG")
burial_ser3 <- seriate(burial_dist, method="BBWRCG")
ord1 <- get_order(burial_ser1)
ord2 <- get_order(burial_ser2)
ord3 <- get_order(burial_ser3)
# Suggested orderings
rbind(ord1, ord2, ord3)

Crit <- c("AR_events", "AR_deviations", "Gradient_raw", "Gradient_weighted")
burial_ord1 <- permute(burial_dist, ord1)
burial_ord2 <- permute(burial_dist, ord2)
burial_ord3 <- permute(burial_dist, ord3)
gahagan_dec_ord <- permute(burial_dist, dec_ord)
gahagan_ca_ord <- permute(burial_dist, ca_ord)

# Comparison between original and ordered:
Results <- list(Original=burial_dist, Ordered1=burial_ord1, Ordered2=burial_ord2, Ordered3=burial_ord3, CA=gahagan_ca_ord, DEC=gahagan_dec_ord)
round(sapply(Results, criterion, method=Crit), 1)

battleship.plot(burial_pct[ord2, ], 
                col="#798E87", 
                cex.labels = .75)
```

# Recalibrate legacy date

```{r legacy, out.width = "100%", dpi = 300, echo=TRUE, warning=FALSE, message=FALSE}
# check for update
library(oxcAAR)
library(rcarbon)
quickSetupOxcal()

# an21
an21 <- data.frame(bp = c(300),
                   std = c(40),
                   names = c("41AN21")
)
an21.cal <- oxcalCalibrate(an21$bp,
                           an21$std,
                           an21$names)
an21.cal

## plot
plot(an21.cal)
```
