---
title: "Raw Material Color"
---

```{r color, out.width = "100%", dpi = 300, echo=TRUE, warning=FALSE, message = FALSE}
# compare colors
library(here)
library(colordistance)
library(recolorize)
library(dplyr)
library(vegan)
library(ape)

# get image paths
images <- colordistance::getImagePaths('images')

# generate color distance matrix
cdm <- imageClusterPipeline(images,
                            lower = FALSE,
                            upper = FALSE,
                            hist.bins = 3,
                            color.space = 'rgb')

# replace NAs with 0
cdm[is.na(cdm)] = 0
# export color distance matrix
write.csv(cdm, file = "color_distance_matrix.csv")
```

## NMDS Ordination

```{r nmdsord, out.width = "100%", dpi = 300, echo=TRUE, warning=FALSE, message=FALSE}
# import color distance matrix
c.dat <- read.csv("color_distance_matrix.csv",
                   header = TRUE,
                   as.is = TRUE)

# omit 81
c.data <- c.dat %>% 
  select(c(X:X80)) %>% 
  filter(X %in% c(56:80))

# import qual data
e.data <- read.csv("qdata.csv",
                   header = TRUE,
                   as.is = TRUE)

# omit 81
e.data <- e.data %>% 
  filter(ColorGroup %in% c('A','B'))

# define add_image function
add_image <- function(obj,
                      x = NULL,
                      y = NULL,
                      width = NULL,
                      interpolate = TRUE,
                      angle = 0) {
  
  # get current plotting window parameters:
  usr <- graphics::par()$usr
  pin <- graphics::par()$pin
  
  # image dimensions and scaling factor:
  imdim <- dim(obj)
  sf <- imdim[1] / imdim[2]
  
  # set the width of the image (relative to x-axis)
  w <- width / (usr[2] - usr[1]) * pin[1]
  h <- w * sf
  hu <- h / pin[2] * (usr[4] - usr[3])
  
  # plot the image
  graphics::rasterImage(image = obj,
                        xleft = x - (width / 2), xright = x + (width / 2),
                        ybottom = y - (hu / 2), ytop = y + (hu/2),
                        interpolate = interpolate,
                        angle = angle)
}

# get image paths (sans img ID81)
images <- colordistance::getImagePaths('images2')

# cdm sans ID81
c.data2 <- as.matrix(c.dat %>% 
    filter(X %in% c(56:80)) %>% 
    select(c(X56:X80))
)

nmds_scores <- scores(metaMDS(comm = as.dist(c.data2)))

# set plot parameters
plot(nmds_scores,
     xlim = c(-0.07, 0.12),
     ylim = c(-0.06, 0.06),
     cex = 1
)

#Create convex hulls that highlight point clusters based on grouping dataframe
ordihull(
  nmds_scores,
  e.data$ColorGroup,
  draw = c("polygon"),
  col = NULL,
  border = c("#798E87","#C27D38")
)

# add images
for (i in 1:length(images)) {
       
    # read image:
    img <- png::readPNG(images[i]) 
    # add image:
    add_image(img,
              x = nmds_scores[i, 1],
              y = nmds_scores[i, 2],
              width = 0.008)
}
```

## Permutational MANOVA

```{r manova, out.width = "100%", dpi = 300, echo=TRUE, warning=FALSE, message=FALSE}
# perMANOVA
# preliminaries
colnames(e.data) <- c('X','site','ColorGroup') # rename columns prior to join
elliptical <- left_join(e.data, c.data, by = "X") # left join by specimen number
elliptical.dist <- elliptical[,4:15] # distance matrix
set.seed(10) # make results reproducible

# model: biface color as a function of color group
el.biface.colour <- adonis2(elliptical.dist ~ ColorGroup,
                            data = elliptical,
                            permutations = 10000,
                            method = 'bray')

## does color differ by ColorGroup?
el.biface.colour
```
